version: "3.9"

services:

    bot:
        build:
            context: .
            dockerfile: docker/Dockerfile-bot
        volumes:
            - .:/app
        restart: always
        networks:
            - chatgpt-telegram-bot
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        build:
            context: .
            dockerfile: docker/Dockerfile-mysql
        restart: always
        ports:
            - "127.0.0.1:3302:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'volume-mysql:/var/lib/mysql'
        networks:
            - chatgpt-telegram-bot
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 3s

networks:
    chatgpt-telegram-bot:
        driver: bridge

volumes:
    volume-mysql: